### PR TITLE
Speed test for the class LibraryRankedSpectrumInfo 

### PR DESCRIPTION
**Pull request by nickshulman**
Test which measures how long it takes for the class LibraryRankedSpectrumInfo to match predicted ions to library spectra. This way we can make sure that my changes in #1050 aren't going to slow down Skyline.

Here is what the output on my machine looks like when I run it:
```
[16:54]   1.0   TestLibraryRankedSpectrumInfoSpeed             (en)
Time to get LibraryRankedSpectrumInfo for Short Peptide 300 times: 00:00:00.0817566
7 matched peaks. Ranked peaks: { 147.1,246.1,359.3,488.4 }
Time to get LibraryRankedSpectrumInfo for Long Peptide 300 times: 00:00:00.2393599
9 matched peaks. Ranked peaks: { 1352.3,1423.8,1475 }
Time to get LibraryRankedSpectrumInfo for Short Peptide with 1 Neutral Loss 300 times: 00:00:00.0897600
4 matched peaks. Ranked peaks: { 322.0948,609.278,707.1737,708.1829 }
Time to get LibraryRankedSpectrumInfo for Long peptide with 1 Neutral Loss 300 times: 00:00:00.5255929
7 matched peaks. Ranked peaks: { 1203.3427,1250.8986,1274.571,1298.2545,1329.6705,1341.2415 }
Time to get LibraryRankedSpectrumInfo for Short peptide with 2 neutral losses 300 times: 00:00:00.2818595
8 matched peaks. Ranked peaks: { 343.2071,403.681,443.1311,610.0934,709.152 }
Time to get LibraryRankedSpectrumInfo for Long peptide with 2 neutral losses 300 times: 00:00:01.5727919
12 matched peaks. Ranked peaks: { 682.7864,1031.3154,1069.0573,1090.3293,1251.3538,1358.1454,1431.825,1489.1063,1497.3608 }
  0 failures, 2.66/3.72/57.1 MB, 11/361 handles, 2 sec.
```

Currently, the times that I get in #1050 are almost exactly the same.

### CODE REVIEW

**Comment by brendanx67** [comment]
The spectrum density matters also. How many spectrum peaks are being matched?

**Comment by nickshulman** [comment]
> The spectrum density matters also. How many spectrum peaks are being matched?

The number of matched peaks was part of the output and varied between 4 and 12 depending on the peptide. I was only passing in "3" for "minPeaks" to the LibraryRankedSpectrumInfo constructor. I did not realize the value that Skyline usually uses is "TransitionGroup.MAX_MATCHED_MSMS_PEAKS" (which is equal to 100). I'll update the test.

**Comment by brendanx67** [comment]
I am talking about the number of spectrum peaks, which should be in the hundreds. I think you should look at some real libraries of spectra.

**Comment by nickshulman** [comment]
> I am talking about the number of spectrum peaks, which should be in the hundreds. I think you should look at some real libraries of spectra.

These are pretty typical looking spectra from NIST yeast and PeptideAtlas phosph spectral libraries. We could certainly add other spectra to the test file if we could think of anything that might have different performance characteristics. (I also still have the big Skyline document with 72000 peptides in it that I selected these 6 peptides from if we need it).

**Pull request merged**
