### PR TITLE
Dotp line graph points should be clickable for changing the active replicate. 

### PR DESCRIPTION
**Pull request by rita-gwen**
Fix for the issue https://skyline.ms/issues/home/issues/details.view?issueId=885.

### CODE REVIEW

**Review by brendanx67 — CHANGES_REQUESTED** [review]
This seems to work as I would expect now. The painting is quite flashy over Remote Desktop. Which I would really like to see fixed. It seems related to the graph painting once without the red cut-off lines and then again with them, which also causes everything in the legend to shift because the red lines are the first elements in the legends. I can give you a demo on Zoom.

**Comment by rita-gwen** [comment]
The fix for double painting was a separate PR and it was not merged into this PR yet at the time when you checked it out. The problem should go away after current master is merged into this branch.

**Comment by brendanx67** [comment]
Can you do the merge? It says it requires manual attention.

**Comment by rita-gwen** [comment]
It is merged now.

**Review by brendanx67 — APPROVED** [review]

**Pull request merged**
