### PR TITLE
* added Sqlite.interop.dll to Skyline.csproj

### PR DESCRIPTION
**Pull request by chambm**

### CODE REVIEW

**Review by nickshulman — APPROVED** [review]

**Comment by chambm** [comment]
I did test that copying Sqlite.interop.dll into the Skyline or Skyline-daily ClickOnce installation folders fixed the wiff2 import issue, but I'm baffled that we could have had this broken since then. Maybe everybody who had the problem had the wiff file to fall back on?

**Comment by chambm** [comment]
@brendanx67 Shall I cherry pick this to release for a patch?

**Comment by nickshulman** [comment]
> @brendanx67 Shall I cherry pick this to release for a patch?

Yes this should be ported to the release branch. We would want this fix to be part of the next patch that we release.

**Comment by brendanx67** [comment]
Agreed.

**Pull request merged**
