### PR TITLE
Added support for building ProteoWizard with VS2022

### PR DESCRIPTION
**Pull request by bspratt**
The changes are limited to the "Boost Build" tool rather than the Boost libraries themselves, so this isn't nearly as dramatic (441 files!) as it may first appear. No ProteoWizard code is changed, other than a handful of .jam files which were refactored for better maintainability next time MSFT rolls out a new Visual Studio version.

### CODE REVIEW

**Comment by chambm** [comment]
Probably due to my Jamroot requirement refactoring.

**Comment by chambm** [comment]
Please do not squash-merge this PR when the time comes. The Boost Build updating commit needs to be kept separate so it can be applied again for the next Boost Build update.

**Comment by bspratt** [comment]
> Please do not squash-merge this PR when the time comes. The Boost Build updating commit needs to be kept separate so it can be applied again for the next Boost Build update.

Noted. 

This feels like one that I definitely want to run through TeamCity first, so the merge will wait for now.

**Comment by bspratt** [comment]
I know we don't want to squash this one, but perhaps you'd like to start a different branch with a more succinct series of commits so that the critical one stands out?

**Comment by chambm** [comment]
I'll squash it locally and force push when I'm ready to merge.

**Comment by bspratt** [comment]
Sounds good. I'll take care of release branch, if you like, once that's in master.

**Comment by bspratt** [comment]
If it's just the linux builds giving trouble, could you go ahead and do the merge so the Skyline (windows) developers can get moving again?

**Comment by chambm** [comment]
If Skyline passes this last commit, I'm going to push the Linux build fix I figured out and merge without waiting for a new round of tests.

**Pull request merged**
