### PR TITLE
Fix BiblioSpec MaxQuant reader finding RAW files

### PR DESCRIPTION
**Pull request by chambm**
* fixed BiblioSpec MaxQuant reader to check up to 4 levels above msms.txt for spectrum files

### CODE REVIEW

**Review by brendanx67 — CHANGES_REQUESTED** [review]
Can we also improve the message? Right now it only tells the user it has looked in the same folder as the msms.txt file.

**Comment by chambm** [comment]
Huh, it should list all the directories it searched in the error message. What was the message you got?

**Comment by chambm** [comment]
@brendanx67 This is the error I see when the file isn't found: `ERROR: Could not find spectrum file 'CPTAC_Set4_725_091509[.mzML|.mzXML]' for search results file 'C:\pwiz.git\pwiz\pwiz_tools\BiblioSpec\tests\inputs\CPTAC_Set4_725_091509.pep.XML' in C:\pwiz.git\pwiz\pwiz_tools\BiblioSpec\tests\inputs\, ../,../../.` The dots at the end indicate it's searching 2 levels up (I tested on a different branch). Are you wanting some kind of text substitution to make the dot directories more intelligible to non-techy users?

**Comment by brendanx67** [comment]
I am not 100% positive the MaxQuant msms.txt error is the same as this one, but yes, I was thinking it would be better to have a multi-line message listing all of the full paths that were considered.

**Comment by brendanx67** [comment]
I guess this is the message I get for MaxQuant in Skyline:
image
It does mention parent or grandparent, but I guess I still prefer a line-separated list of full paths, especially now that we are willing to search 4 folders up or 5 folders in total.

**Comment by brendanx67** [comment]
This is a different issue, I know, but also when I click "Retry" on this message it can take 10-20 seconds before I see a progress bar appear in the status bar. It seems to appear with some green filled in, but it should appear immediately with 0% progress to make it more clear that the work requested is happening.

**Comment by brendanx67** [comment]
Also, we need to pre-check all of the raw data files before extracting spectra from any of them so that the user gets a message about what is missing as soon as possible. You can see that the message above is about just 1 missing file but there are 30, and if I move 29 of them to the right location, then BlibBuild will labor for a REALLY long time extracting spectra from the other 29:
image
and then finally give me the following error that one is missing.
image

**Comment by brendanx67** [comment]
So, I am thinking the message should go more like this:

Could not find external spectrum files with the following base names:

{basenames line separated}

In any of the following folders:

{checked folders line separated}

...

**Comment by chambm** [comment]
Ah, I had forgotten about that MaxQuant-specific error message. It parses/overrides the BiblioSpec error.

> So, I am thinking the message should go more like this:
> 
> Could not find external spectrum files with the following base names:
> 
> {basenames line separated}
> 
> In any of the following folders:
> 
> {checked folders line separated}
> 
> ...
How about this?
```
While searching for spectrum files for the search results file 'C:\pwiz.git\pwiz\pwiz_tools\BiblioSpec\tests\inputs\test.msms.txt', BiblioSpec could not find matches for the following basenames:
D20110201_Exp2_TBK1_01
D20110201_Exp2_TBK1_02
D20110201_Exp2_TBK1_03
D20110201_Exp2_TBK1_04
D20110201_Exp2_TBK1_05
D20110201_Exp2_TBK1_06
D20110201_Exp2_TBK1_07
D20110201_Exp2_TBK1_08
D20110201_Exp2_TBK1_09
D20110201_Exp2_TBK1_10
D20110201_Exp2_TBK1_11
D20110201_Exp2_TBK1_12
D20110201_Exp2_TBK1_13
D20110201_Exp2_TBK1_14
D20110201_Exp2_TBK1_15
D20110201_Exp2_TBK1_16

In any of the following directories:
C:\pwiz.git\pwiz\pwiz_tools\BiblioSpec\tests\inputs\
C:\pwiz.git\pwiz\pwiz_tools\BiblioSpec\tests\
C:\pwiz.git\pwiz\pwiz_tools\BiblioSpec\

Checking basenames with one of the following file extensions:
.mz5
.mzML
.raw
.wiff
.d
.lcd
.mzXML
.cms2
.ms2
.mgf
```
That's straight from BiblioSpec. The Skyline version that gets shown in the dialog box could be tweaked a bit.

**Comment by brendanx67** [comment]
I don't think we want to name "BiblioSpec". Just say "could not find". Skyline users don't understand that something called "BiblioSpec" is running in the background.

**Comment by brendanx67** [comment]
Also, wasn't the original request to go up 4 levels? Why does this only show 2 levels above the folder containing the msms.txt file?

**Comment by chambm** [comment]
It thought it was appropriate for BiblioSpec's error to mention BiblioSpec (perhaps should be BlibBuild), otherwise the error text without a subject seemed somewhat awkward to me. That would be tweaked out in Skyline which has to parse the message and modify it. But it could be left out for BiblioSpec as well. There's some awkwardness in this error no matter what. 

Skyline's tweaked version is going to be a loooong error dialog. Should I comma-separate the extensions?

My development for this change started on a different branch, but I'll be rebasing it here.

**Comment by brendanx67** [comment]
How about this?

For the search results file {1} the following base names could not be found
with any of the extensions ({2}):
{3}
In any of the following folders:
{4}

I don’t want a subject in this message. This is definitely an improvement
on what you have. Yes, comma separate the extensions.

**Comment by chambm** [comment]
Look good?
image
Should I show only the filename part of the msms.txt?

**Comment by brendanx67** [comment]
I think the full path is fine. I would like to see the extension list near the top (as I had it in my message). I am not in love with your starting message over mine, but if you want to keep it closer to yours, then it should read:

"... could not find matches for any of the following basenames with any of the supported extensions (mz5, ..., or mgf):"

This makes it clearer how you are approaching "matching" a basename. Otherwise, I need to read to the very bottom of the message to know the names you have actually tried.

**Comment by chambm** [comment]
image

**Comment by brendanx67** [comment]
Looks good. I might consider adding blank lines after the colon (:) lines.
Though, that obviously requires a slightly taller form, but separates the
text better.

**Pull request merged**
