### PR TITLE
Get CE from Bruker BAF format

### LINKED ISSUE #2087: How to keep the value of collision energy
Hi expert,

I would like to consult how to set parameters to keep the values of collision energy of MS2 DDA data after transferring into the format of .mzml. I have tried many settings, ending up with zero for collision energy. I appreciate any help very much.

Bests,
Muyao

### PR DESCRIPTION
**Pull request by chambm**
- increased maximum worker thread count for msconvert to 16
- added support for getting CE from Bruker BAF format

Closes #2087

### CODE REVIEW

**Comment by MuyaoXi9271** [comment]
Hi Matt Chambers,

I tried to convert .d file into .mzML file no matter whether I selected subset or peak picking. I still can not get the value of collision energy from either of them.  What parameters I should pay attention to in order to let the value of collision energy come out?

Bests,
Muyao

**Comment by chambm** [comment]
Are you using 3.0.22126 or later?

**Comment by MuyaoXi9271** [comment]
Hi, it works. Thanks very much

Bests,
Muyao

**Comment by MuyaoXi9271** [comment]
Hi Matt,

I repeated the same procedures by using msconvert on the same file acquired from another polarity. The value of collision energy becomes zero again. Do you need me to provide the analysis.sqlite file to check?


Bests,
Muyao

**Comment by chambm** [comment]
Yes just send me the .sqlite file. I'm guessing maybe the CE values are negative.

**Comment by MuyaoXi9271** [comment]
Hi Matt,

Regarding GDPR, I have sent the .sqlite file to your Gmail. Please check it.
It could be better to let me know when you have done.


Bests,
Muyao

**Comment by chambm** [comment]
Yep, negative CE. I'll fix pwiz to use that as an absolute value (since it already knows the polarity is negative).

**Comment by MuyaoXi9271** [comment]
Thanks very much. I will download the updated version when you have done. Please let me know. Thanks again.

Bests,
Muyao

**Comment by MuyaoXi9271** [comment]
Hi Matt,

May I ask how the new version is going? Can I download the updated version now?


Bests,
Muyao

**Comment by chambm** [comment]
Will be fixed in https://github.com/ProteoWizard/pwiz/pull/2248

**Pull request merged**
