### PR TITLE
[mz5] fixed typo in data set ChromatogramTime

### PR DESCRIPTION
**Pull request by jeleclaire**
Fixed the typo in data set "ChomatogramTime" into "ChromatogramTime". Backward compatibility ensured.

### CODE REVIEW

**Comment by chambm** [comment]
Thanks for the PR. I'd noticed that before, but left it alone because I didn't want to break anybody else's reader. Not that I'm actually aware of any other readers. Do you know of any?

**Comment by jeleclaire** [comment]
Good point. I always thought OpenMS would support mz5 but I couldn't find a hint.

**Comment by brendanx67** [comment]
Can we please decide whether we want this change and either merge it or close it?

**Comment by jeleclaire** [comment]
I think, this change should be incorporated. First, even if it is just a typo, it is not the first time it was discovered and if it is not changed, it will be rediscovered again and again. Second, there were changes to the mz5 core anyway, so maybe now is a good time point to include it.

**Comment by brendanx67** [comment]
I agree. As long as we are backward compatible, which it looks like we are, then I think we should just fix this before there are more readers that would be broken by the fix.

**Pull request merged**
