### PR TITLE
Bruker method export

### PR DESCRIPTION
**Pull request by kaipot**

### CODE REVIEW

**Comment by chambm** [comment]
@kaipot Can you handle updating the Skyline-side to make use of the progress delegate?

**Comment by kaipot** [comment]
> @kaipot Can you handle updating the Skyline-side to make use of the progress delegate?

Yes, the test is working for me now, I'll make the changes in Skyline.

**Comment by kaipot** [comment]
> > @kaipot Can you handle updating the Skyline-side to make use of the progress delegate?
> 
> Yes, the test is working for me now, I'll make the changes in Skyline.

I've added this to Skyline. By the way Matt, the test changes the prmsqlite file. Maybe it should copy it (or not write)?

**Comment by brendanx67** [comment]
That should get fixed. We don't want a test that causes a tree diff.

**Comment by chambm** [comment]
Should be ready to merge now. Kaipo I'm assuming you tested that the progress/cancel function is working ok in Skyline. :)

**Comment by kaipot** [comment]
> Should be ready to merge now. Kaipo I'm assuming you tested that the progress/cancel function is working ok in Skyline. :)

Yep, I think this is good to go. I will send out a link to the artifacts once the build is done.

**Pull request merged**
