### PR TITLE
Change ZedGraphClipboardTest to only use the System clipboard if "Run…

### PR DESCRIPTION
**Pull request by nickshulman**
…PerfTests" is true.

### CODE REVIEW

**Comment by chambm** [comment]
I don't understand how but it looks like this PR broke the Windows x86 build. The ConsoleImportPeptideSearchTest is failing (which also triggers the uninstall test failure but that's derivative of any TestData test failing):
https://teamcity.labkey.org/viewLog.html?buildId=1543862&tab=buildResultsDiv&buildTypeId=bt19

I just reran an older PR (1739) that hasn't been updated to the latest master since this PR was merged and it still passes:
https://teamcity.labkey.org/viewLog.html?buildId=1545347&tab=queuedBuildOverviewTab

**Comment by chambm** [comment]
Ping @nickshulman (not sure if you got a notification because the PR is merged)

**Comment by nickshulman** [comment]
@chambm, isn't everything passing on master now?

**Comment by chambm** [comment]
Well that is mysterious. Let's continue to observe. If it's really this intermittent then it could certainly have been an earlier PR.

**Comment by chambm** [comment]
Still flaky but very mysterious that it's only flaky on TC:
https://teamcity.labkey.org/project.html?buildTypeId=bt19&tab=testDetails&testNameId=-5468656425461629408&projectId=ProteoWizard&order=START_DATE_DESC&page=1

Maybe because the nightly tests don't do x86? Should I just pause the x86 Skyline configs @brendanx67 ?

**Comment by nickshulman** [comment]
What code is writing out the message "Cannot process request because the process (3604) has exited." to the log file? Are we outputting that somewhere in our code, or is the operating system doing this.

If I run the ConsoleImportPeptideSearchTest on my computer about 5,000 times, I can eventually get a NullReferenceException in  "CommandProgressMonitor.Wait". That failure does not look anything like what we are seeing on TeamCity, so I imagine it is not related to this failure.

**Comment by chambm** [comment]
The `Cannot process request because the process (3604) has exited` error is from calling `Process.Kill()` on a process that's already exited. However that's usually delivered with an InvalidOperationException. It seems very likely that that's happening on the BlibBuild call but I can't see how it's swallowing the rest of the exception details but still delivering the message. The original failure, including that message, was before I added the try/finally with an extra `proc.Kill()`, so it shouldn't be that:
https://teamcity.labkey.org/viewLog.html?buildId=1556374&buildTypeId=bt19&tab=buildLog

**Pull request merged**
