### PR TITLE
Tweaks to deal with new warnings from latest ReSharper.

### PR DESCRIPTION
**Pull request by bspratt**
This one is very popular:
[https://www.jetbrains.com/help/resharper/UsageOfDefaultStructEquality.html](https://www.jetbrains.com/help/resharper/UsageOfDefaultStructEquality.html) 
It suggests that default generated runtime comparisons for structs are usually slow, and we should use our own code for equality checks. I've done so, but I worry a bit that we now have more code to maintain in the event that a member is added to a struct. (Interestingly in the act of doing this, I noticed that Model.TransitionGroup.LossId already has its own equality comparer, but doesn't include all its members in that - I've left a CONSIDER comment there)

### CODE REVIEW

**Comment by bspratt** [comment]
Brendan isn't convinced that all these new equality methods are worth the churn, and I'm not either. Backing those out and busting that Warning down to a Suggestion is certainly a reasonable option.

**Comment by bspratt** [comment]
BTW @brendanx67 that curious equality method I mentioned in Model.TransitionGroup.LossId is yours - it looks like we're forbidding its use between precursor and fragment, but I wonder if we want to see if fragment types are equal (and if we don't, maybe we can have a comment saying why we don't)

**Comment by dshteyn** [comment]
I guess the way to verify is to time the execution with and without the change and see the actual difference in runtimes. This might entail a greater effort than it is worth.

**Comment by bspratt** [comment]
>> This might entail a greater effort than it is worth.
I think that's the feeling, yeah.

**Comment by brendanx67** [comment]
Our general rubric is 1) make the code as readable and maintainable as
possible, 2) focus on performance in bottleneck situations and prove the
value of more complex code with profiling statistics.

**Comment by brendanx67** [comment]
Especially in UI, you could waste a lot of time and complexity optimizing
code that has no visible impact on the user experience.

**Comment by bspratt** [comment]
I'm going to issue a new PR with a clean history, and that warning busted down to a suggestion.

**Pull request closed without merging**
