### PR TITLE
SkylineNightly: after 30 minutes of failing to download SkylineTester .lastFinished build,…

### PR DESCRIPTION
**Pull request by bspratt**
…  don't give up as we formerly did but instead go an additional 90 minutes of retrying, alternating between trying for .lastFinished vs .lastSuccessful builds.

By waiting to fail over to the potentially stale .lastSuccessful build, we get some testing done on relatively recent code while still being alerted to a problem thanks to the lower test count.

### CODE REVIEW

**Comment by chambm** [comment]
It makes sense to try lastFinished for a while before trying lastSuccessful, but it doesn't make sense to me to alternate between them in the second phase. What's the logic there?

**Comment by chambm** [comment]
IMO it would make more sense to just fall back to lastSuccessful. If it turns out to be a connectivity problem, lastSuccessful is almost certainly going to be the same build as lastFinished. And if it was due to a build failure, then there are 2 possibilities: a new build is running and when it finishes successfully then lastSuccessful will be the same as lastFinished, or a new build isn't running and lastSuccessful will be the only working option.

**Comment by bspratt** [comment]
Fair enough, Ill make the change.

**Comment by chambm** [comment]
The container failure is fixed in #1744 and I'm working on the debug failures due to changing over to VS 2019 as the default TC toolset.

**Pull request merged**
