### PR TITLE
Fix location of drop targets when multiple screens have different dpi

### PR DESCRIPTION
**Pull request by nickshulman**
Fixed display of dockable window drop targets when second monitor has different "Scale" (dots per inch) (reported most recently by Juan)

The source code for this change is in this pull request:
https://github.com/uw-maccosslab/developers/pull/2

### CODE REVIEW

**Comment by brendanx67** [comment]
Nice! This one drives me crazy, as I usually have different scales on my two monitors at home. I just switched to 100% scaling on both monitors for Skyline-Online today. Otherwise, when not demoing, I just "feel around" for the drop targets. It will be nice to have a fix.

**Comment by brendanx67** [comment]
Can you merge this back to 22.2?

**Comment by nickshulman** [comment]
There is still a bit of a problem where, if the Skyline window is spread across two monitors with different resolutions, it's not possible to drop on a drop target which is on the other screen.

image

**Comment by brendanx67** [comment]
Worked for my tests with monitors at 1920x1080@100% and 2160x3840@150% starting the main window on both screens for the main window.

It still does not work, however, for docking multiple windows into a floating window. There I am still not seeing docking indicators for the floating windows. Though, the cursor hit-testing is working correctly (as it always did for the main window), you just need to hunt around for what you are looking for, knowing when you have it because of the blue shaded rectangle which also shows up correctly. It is just the docking indicators that are entirely missing on my screens.

**Comment by brendanx67** [comment]
image

**Comment by brendanx67** [comment]
image

**Comment by brendanx67** [comment]
It is an improvement. So, maybe we should merge this fix but leave an issue active for the floating window case.

**Comment by nickshulman** [comment]
It would be better to comment on the code changes in the docking windows source code repository:
https://github.com/uw-maccosslab/developers/pull/2

I think the fix I have there happens to fix the bug, but the reasoning behind it is completely flawed.
Also, I did not realize there were two different states of DockIndicator objects: sometimes their DockPane is null, and sometimes not null, and in the latter case, the DockPanel rectangle is irrelevant.

I think I'm close to figuring out what the actual right fix might be.

**Comment by brendanx67** [comment]
Definitely want this in the 22.2 patch for Sunday night.

**Pull request merged**
