### PR TITLE
Missing rdotp line (issue 1033)

### PR DESCRIPTION
**Pull request by rita-gwen**

### CODE REVIEW

**Review by nickshulman — COMMENTED** [review]
If the peptide has transitions with multiple charge states, there could be multiple TransitionGroupDocNode's that have a dot product. 

It might make the most sense to show the average dot product across those TransitionDocNode's instead of just showing the dot product from the first TransitionGroupDocNode.

**Comment by rita-gwen** [comment]
Thank you for the review. I re-wrote it to show the average, as suggested.

**Comment by brendanx67** [comment]
Please don't merge yet. I wan't completely satisfied with my review, but go
pulled away to other things.

**Comment by rita-gwen** [comment]
OK

**Pull request merged**
