### PR TITLE
Fix unescaped ampersands in msfragger pepXML output

### PR DESCRIPTION
**Pull request by bspratt**

### CODE REVIEW

**Comment by brendanx67** [comment]
This seems overly simplistic. What if there is an entity in the XML? This would double escape the ampersand in the entity. Ideally, you would be looking for an ampersand in a specific attribute and even checking for a semicolon within 5 characters (e.g. &quot;)

**Comment by brendanx67** [comment]
You don't want to create an instance of &amp;amp;quot;

**Comment by bspratt** [comment]
Agreed, the Regex is looking only for unescaped ampersands: "&(?!amp;|lt;|gt;|quot;|apos;)"

**Comment by bspratt** [comment]
image

**Comment by brendanx67** [comment]
> Agreed, the Regex is looking only for unescaped ampersands: "&(?!amp;|lt;|gt;|quot;|apos;)"

I  missed that subtlety. Thought it was a string.replace().

That covers the named entities. Maybe that is good enough. For completeness you would have to include:

&amp;#\d\d;
&amp;#x\x\x;

**Comment by bspratt** [comment]
OK, added those and made the whole thing less subtle, hopefully

**Review by brendanx67 — APPROVED** [review]

**Review by chambm — APPROVED** [review]
Looks good.

**Pull request merged**
