### PR TITLE
Fix compile with latest VC2017 update

### PR DESCRIPTION
**Pull request by chambm**
* updated boost-build to master to (3d4fa4162d05d155539d247998a499ec7c5dcd69)
@bspratt try this

### CODE REVIEW

**Comment by chambm** [comment]
All those damn typo fixes made it a lot harder than it could have been...

**Comment by bspratt** [comment]
Still gives me "'cl' is not recognized as an internal or external command, operable program or batch file." - but perhaps I'm using it wrong?

pwiz_tools\build-apps.bat 64 variant=release --i-agree-to-the-vendor-licenses --without-compassxtract --msparser-path="C:\PROGRA~1\MATRIX~1\MASCOT~1\vs2015" toolset=msvc-14.1

**Comment by chambm** [comment]
I'm not able to reproduce, and I did go ahead and update my Visual Studio to 15.8.9. Email me your environment variables in a stock cmd prompt. What happens when you run: `libraries\boost-build\src\engine\vswhere_usability_wrapper.cmd`? It should set: `VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\` (but with Enterprise in your case)

**Comment by bspratt** [comment]
No such luck:

Microsoft Windows [Version 10.0.17134.590]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\bspratt>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\bspratt\AppData\Roaming
APR_ICONV_PATH=C:\Program Files (x86)\Subversion\iconv
BOOST_ROOT=I:\Dev\boost_1_56_0
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=BSPRATT-UW2
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\bspratt
INTEL_LICENSE_FILE=C:\Program Files (x86)\Common Files\Intel\Licenses
LOCALAPPDATA=C:\Users\bspratt\AppData\Local
LOGONSERVER=\\BSPRATT-UW2
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\bspratt\OneDrive
OS=Windows_NT
Path=C:\Program Files (x86)\Intel\iCLS
Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS
Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Agilent\MassHunter\Workstation\IMS\B.07.02\\Bin;C:\MYSTUFF;C:\PROGRAM
FILES (X86)\NOTEPAD++;C:\PROGRAM FILES (X86)\MICROSOFT SQL
SERVER\100\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL
SERVER\100\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL
SERVER\100\DTS\BINN\;C:\PROGRAM FILES
(X86)\WINMERGE;C:\UNXUTILS\USR\LOCAL\WBIN;I:\DEV\PROTEOWIZARD\BUILD-NT-X86\PWIZ_TOOLS\COMMANDLINE\0D99B0746140928B164C19149A4C111F;C:\PROGRAM
FILES\7-ZIP;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 10.0\TEAM
TOOLS\PERFORMANCE TOOLS\X64;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO
10.0\TEAM TOOLS\PERFORMANCE TOOLS;C:\PROGRAM FILES
(X86)\SUBVERSION\BIN;C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\WINDOWS
PERFORMANCE TOOLKIT\;C:\PROGRAM FILES\MICROSOFT SQL
SERVER\110\TOOLS\BINN\;C:\PROGRAM FILES\IBM\RATIONALPURIFYPLUS;C:\Program
Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth
Software\syswow64;C:\Program Files (x86)\Common Files\Micro
Focus\NMShared\CTI\11.1;C:\Program Files (x86)\Microsoft
SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL
Server\120\Tools\Binn\;C:\Program
Files\EmEditor;C:\Users\bspratt\.dnx\bin;C:\Program Files\Microsoft
DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program
Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files
(x86)\NVIDIA Corporation\PhysX\Common;C:\Program
Files\TortoiseSVN\bin;C:\Program Files (x86)\GitExtensions\;C:\Program
Files\Git\cmd;C:\Program Files (x86)\Intel\UCRT\;C:\Program
Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine
Components\IPT;C:\Program
Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
Files\TortoiseGit\bin;C:\Users\bspratt\AppData\Local\Microsoft\WindowsApps;c:\Program
Files (x86)\Microsoft Visual Studio\Installer;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\bspratt\AppData\Local\Temp
TMP=C:\Users\bspratt\AppData\Local\Temp
USERDOMAIN=bspratt-UW2
USERDOMAIN_ROAMINGPROFILE=bspratt-UW2
USERNAME=bspratt
USERPROFILE=C:\Users\bspratt
VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio
11.0\Common7\Tools\
VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio
12.0\Common7\Tools\
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio
14.0\Common7\Tools\
windir=C:\WINDOWS
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

C:\Dev\master_clean>libraries\boost-build\src\engine\vswhere_usability_wrapper.cmd
could not find "vswhere"

[Manually update path to include  c:\Program Files (x86)\Microsoft Visual
Studio\Installer  ]
C:\Dev\master_clean>which vswhere.exe
c:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

C:\Dev\master_clean>libraries\boost-build\src\engine\vswhere_usability_wrapper.cmd
could not find "vswhere"

**Comment by chambm** [comment]
`set DEBUG_HELPER=1`
Then rerun vswhere_usability_wrapper.cmd and show the output.

**Comment by bspratt** [comment]
C:\Dev\master_clean>set DEBUG_HELPER=1

C:\Dev\master_clean>libraries\boost-build\src\engine\vswhere_usability_wrapper.cmd

C:\Dev\master_clean>setlocal

C:\Dev\master_clean>set "InstallerPath=C:\Program Files (x86)\Microsoft
Visual Studio\Installer"

C:\Dev\master_clean>if not exist "C:\Program Files (x86)\Microsoft Visual
Studio\Installer" set "InstallerPath=C:\Program Files\Microsoft Visual
Studio\Installer"

C:\Dev\master_clean>if not exist "C:\Program Files (x86)\Microsoft Visual
Studio\Installer" goto :no-vswhere

C:\Dev\master_clean>set Path=C:\Program Files (x86)\Intel\iCLS
Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS
Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Agilent\MassHunter\Workstation\IMS\B.07.02\\Bin;C:\MYSTUFF;C:\PROGRAM
FILES (X86)\NOTEPAD++;C:\PROGRAM FILES (X86)\MICROSOFT SQL
SERVER\100\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL
SERVER\100\TOOLS\BINN\;C:\PROGRAM FILES\MICROSOFT SQL
SERVER\100\DTS\BINN\;C:\PROGRAM FILES
(X86)\WINMERGE;C:\UNXUTILS\USR\LOCAL\WBIN;I:\DEV\PROTEOWIZARD\BUILD-NT-X86\PWIZ_TOOLS\COMMANDLINE\0D99B0746140928B164C19149A4C111F;C:\PROGRAM
FILES\7-ZIP;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 10.0\TEAM
TOOLS\PERFORMANCE TOOLS\X64;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO
10.0\TEAM TOOLS\PERFORMANCE TOOLS;C:\PROGRAM FILES
(X86)\SUBVERSION\BIN;C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\WINDOWS
PERFORMANCE TOOLKIT\;C:\PROGRAM FILES\MICROSOFT SQL
SERVER\110\TOOLS\BINN\;C:\PROGRAM FILES\IBM\RATIONALPURIFYPLUS;C:\Program
Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth
Software\syswow64;C:\Program Files (x86)\Common Files\Micro
Focus\NMShared\CTI\11.1;C:\Program Files (x86)\Microsoft
SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL
Server\120\Tools\Binn\;C:\Program
Files\EmEditor;C:\Users\bspratt\.dnx\bin;C:\Program Files\Microsoft
DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program
Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files
(x86)\NVIDIA Corporation\PhysX\Common;C:\Program
Files\TortoiseSVN\bin;C:\Program Files (x86)\GitExtensions\;C:\Program
Files\Git\cmd;C:\Program Files (x86)\Intel\UCRT\;C:\Program
Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine
Components\IPT;C:\Program
Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
Files\TortoiseGit\bin;C:\Users\bspratt\AppData\Local\Microsoft\WindowsApps;c:\Program
Files (x86)\Microsoft Visual Studio\Installer;;C:\Program Files
(x86)\Microsoft Visual Studio\Installer

C:\Dev\master_clean>where vswhere  2>nul 1>nul

C:\Dev\master_clean>if errorlevel 1 goto :no-vswhere

C:\Dev\master_clean>set VSWHERE_REQ=-requires
Microsoft.VisualStudio.Component.VC.Tools.x86.x64

C:\Dev\master_clean>set VSWHERE_PRP=-property installationPath

C:\Dev\master_clean>set VSWHERE_LMT=-version "[15.0,16.0)"

C:\Dev\master_clean>vswhere -prerelease  1>nul

C:\Dev\master_clean>if "" == "prerelase" set VSWHERE_WITH_PRERELASE=1

C:\Dev\master_clean>if not errorlevel 1 if "" == "1" set
"VSWHERE_LMT=-version "[15.0,16.0)" -prerelease"

C:\Dev\master_clean>SET VSWHERE_ARGS=-latest -products * -requires
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property
installationPath -version "[15.0,16.0)"

C:\Dev\master_clean>for /F "usebackq tokens=*" %i in (`vswhere -latest
-products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
-property installationPath -version "[15.0,16.0)"`) do (
endlocal


 set "VS150COMNTOOLS=%i\Common7\Tools\"
 exit /B 0
)

C:\Dev\master_clean>endlocal

C:\Dev\master_clean>echo could not find "vswhere"
could not find "vswhere"

C:\Dev\master_clean>exit /B 1

C:\Dev\master_clean>

*That message is misleading: it does find vswhere but no output happens*

C:\Dev\master_clean>vswhere -latest -products * -requires
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property
installationPath -version "[15.0,16.0)"

*Drop the requires argument and:*

C:\Dev\master_clean>vswhere -latest -products * -property installationPath
-version "[15.0,16.0)"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise

C:\Dev\master_clean>

**Comment by bspratt** [comment]
So maybe it's uncovering a flaw in my installation. In the IDE the About
box shows:

Microsoft Visual Studio Enterprise 2017
Version 15.9.8
VisualStudio.15.Release/15.9.8+28307.481
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings,
a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft
Azure Tools.

CustomizeVSWindowTitle 3   1.0
Information about my package

JetBrains ReSharper Ultimate 2018.1.2    Build 112.0.20180530.113618
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more
information about ReSharper Ultimate, visit
http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet,
visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools
 2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and
settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by chambm** [comment]
Yeah, looks like your C++ got zapped somehow. The error message could be a lot better in the "usability" wrapper though!
```
Microsoft Visual Studio Community 2017 
Version 15.9.8
VisualStudio.15.Release/15.9.8+28307.481
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA351
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

JavaScript Language Service   2.0
JavaScript Language Service

JetBrains ReSharper Ultimate 2018.2.3   Build 182.0.20180912.70621
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61902.21100
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by bspratt** [comment]
yeah, it went away... progress, thanks!

[image: image.png]

**Comment by bspratt** [comment]
So in the end it was just that the Visual Studio update disable my C++ installation. All working now with these changes, which were likely a goose chase, sorry.

**Comment by chambm** [comment]
Oh well, at least the typo fixes are integrated so the next merge will be less painful. :)

**Comment by bspratt** [comment]
:shipit: Thanks!

**Pull request merged**
