### PR TITLE
fix unexpected behavior with ion mobility values in spectral libraries (and no ion mobility library)

### PR DESCRIPTION
**Pull request by bspratt**
SrmDocument.Settings.GetIonMobilities(LibKey[] targetIons, MsDataFileUri filePath) wasn't retrieving ion mobility values from spectral libraries unless filePath was specified - in the unspecified case it should be taking the median value for all files referenced in the library

### CODE REVIEW

**Comment by bspratt** [comment]
image

**Review by brendanx67 — CHANGES_REQUESTED** [review]
Can you add a test to prove what was broken now works?

**Comment by bspratt** [comment]
> Can you add a test to prove what was broken now works?

Done.

**Comment by bspratt** [comment]
I'd like to backport this to release.

**Review by brendanx67 — APPROVED** [review]
Looks good. Okay to cherry pick to release.

**Pull request merged**
