### PR TITLE
The import peptide search wizard dialog is taller than we'd like when IMS is in play…

### PR DESCRIPTION
**Pull request by bspratt**
…, so go for a more careful arrangement of the Full Scan Settings tab.

We save some real estate when IMS values are found in the spectral library by no longer asking the user if they want to use them (of course they do) although we also now will accept 0 as a valid resolving power meaning "no filtering" (which actually makes sense - divide by 0 gives an infinitely wide window)

image

### CODE REVIEW

**Review by brendanx67 — CHANGES_REQUESTED** [review]
Please make the spacing consistent with the space between MS1 and MS2. This should pack things in even a bit more. All of the spacing between MS1, MS2, high-selectivity, IMS, RT filtering should be consistent.

**Comment by bspratt** [comment]
> Please make the spacing consistent with the space between MS1 and MS2. This should pack things in even a bit more. All of the spacing between MS1, MS2, high-selectivity, IMS, RT filtering should be consistent.

image

**Comment by bspratt** [comment]
> What happened to the checkbox? I think it needs to stay and be part of the consistent spacing.

Oops, thanks for noticing. Accidentally left out of the formatting due to being disabled, not what we meant.

**Comment by bspratt** [comment]
image

**Review by brendanx67 — APPROVED** [review]

**Comment by brendanx67** [comment]
Looks right to me.

**Comment by bspratt** [comment]
I suppose there are tutorial screenshots that should be updated?

**Comment by brendanx67** [comment]
I think only the diaPasef tutorial will really need it. The others should not change perceptibly when the IMS group box is hidden.

**Pull request merged**
