### PR TITLE
* fixed percolator's xerces DLL not having its MSVC runtime side-by-side

### PR DESCRIPTION
**Pull request by chambm**
* fixed percolator's xerces DLL not having its MSVC runtime side-by-side (I had to change to a different Xerces DLL that depends on VC9 instead of VC10 because we are already redistributing VC9, but don't have VC10, and Xerces didn't have builds against anything newer; it's the same version of Xerces though)

I'm kind of surprised we haven't heard of anybody else who has run into this. I guess not that many people have tried the DDA search yet.

[cp-to-release]

### CODE REVIEW

**Comment by chambm** [comment]
@brendanx67 do you want this in release?

**Comment by brendanx67** [comment]
Sure. Installing fully side-by-side is ideal.

**Comment by chambm** [comment]
[cp-to-release]

**Comment by chambm** [comment]
[cp-to-release]

**Comment by chambm** [comment]
[cp-to-release]

**Pull request merged**
