### PR TITLE
- updated Waters MassLynx SDK

### PR DESCRIPTION
**Pull request by chambm**
- updated Waters MassLynx SDK (new version provides the first iteration of SONAR conversion functions)
- fixed frame-level TIC for Waters IMS/SONAR data (under fast metadata)
* added unit tests for MSe, HDMSe, HDMRM, HDDDA, SONAR, including testing combineIonMobilitySpectra alternatives
* removed Hungarian notation prefix from eIonMobilityUnits

### CODE REVIEW

**Comment by chambm** [comment]
Still waiting on Waters to provide another SDK update to give us bin -> m/z conversion, and how to make the calibration files.

**Comment by bspratt** [comment]
Looks like something went sidesways, per the TC build (I find that I am a convert to the auto-pull-request-build idea):

 SpectrumList_IonMobility_Test.cpp
[08:28:34][Step 1/1] Z:\pwiz\pwiz\utility\bindings\CLI\analysis\SpectrumList_IonMobility_Test.cpp(49) : error C3083: 'eIonMobilityUnits': the symbol to the left of a '::' must be a type
[08:28:34][Step 1/1] Z:\pwiz\pwiz\utility\bindings\CLI\analysis\SpectrumList_IonMobility_Test.cpp(49) : error C2039: 'drift_time_msec' : is not a member of 'pwiz::CLI::analysis::SpectrumList_IonMobility'
[08:28:34][Step 1/1]         z:\pwiz\build-nt-x86\pwiz\utility\bindings\cli\msvc-12.0\rls\adrs-mdl-64\thrd-mlt\us-clr-tr\pwiz_bindings_cli.dll : see declaration of 'pwiz::CLI::analysis::SpectrumList_IonMobility'
[08:28:34][Step 1/1] Z:\pwiz\pwiz\utility\bindings\CLI\analysis\SpectrumList_IonMobility_Test.cpp(49) : error C2065: 'drift_time_msec' : undeclared identifier
[08:28:34][Step 1/1] Z:\pwiz\pwiz\utility\bindings\CLI\analysis\SpectrumList_IonMobility_Test.cpp(50) : error C3083: 'eIonMobilityUnits': the symbol to the left of a '::' must be a type
[08:28:34][Step 1/1] Z:\pwiz\pwiz\utility\bindings\CLI\analysis\SpectrumList_IonMobility_Test.cpp(50) : error C2039: 'drift_time_msec' : is not a member of 'pwiz::CLI::analysis::SpectrumList_IonMobility'
[08:28:34][Step 1/1]         z:\pwiz\build-nt-x86\pwiz\utility\bindings\cli\msvc-12.0\rls\adrs-mdl-64\thrd-mlt\us-clr-tr\pwiz_bindings_cli.dll : see declaration of 'pwiz::CLI::analysis::SpectrumList_IonMobility'
[08:28:34][Step 1/1] Z:\pwiz\pwiz\utility\bindings\CLI\analysis\SpectrumList_IonMobility_Test.cpp(50) : error C2065: 'drift_time_msec' : undeclared identifier

**Comment by chambm** [comment]
Should I merge this now or wait for more conversion functions from Waters?

**Comment by bspratt** [comment]
Did you say we have a newer Waters SDK? If so, let's update this branch.

**Comment by chambm** [comment]
@bspratt Updated. But there's still only a drift time -> CCS converison, no CCS -> drift time. But I did add a unit tests for that function. It doesn't actually use the raw data, it just reads the mob_cal.csv file and does some math as far as I can tell.

**Comment by bspratt** [comment]
We can't commit this until they have bidirectional DT <-> CCS conversion. From our perspective the whole idea of CCS is to be able to use it as a library property from which you convert to appropriate ion mobility values.

**Comment by chambm** [comment]
Fair enough, but I'll merge this in the meantime (when I fix the apparent crashes I caused in TestRunner) because it has some other "nice to have" fixes and shouldn't hurt anything. It doesn't leak memory, I checked that (albeit only the 64-bit DLLs).

**Comment by bspratt** [comment]
If understand the code, though, it claims to do conversion both ways but doesn't in fact do so. That's a problem for Skyline.

**Comment by chambm** [comment]
Well, it always converts to 0 in the other direction! What's so wrong with that? :) Since there's only 1 "canConvert" function, it's either all or nothing. It seems silly to split it into 2 functions, so since Skyline is the only one using that function for now, I'll just revert it to false for Waters.

**Comment by bspratt** [comment]
Skyline needs both directions. If given a CCS library value, we convert that to an ion mobility value for chromatogram extraction filtering. We also will search for peaks in the IM dimension on unfiltered data, and use that to come up with CCS values which can be placed in libraries. So, yeah, we assume it goes in both directions but it never occurred to me that a vendor wouldn't provide both.

**Comment by bspratt** [comment]
So, yeah, set it to false and carry on, thanks!

**Pull request merged**
