### PR TITLE
Added support for heavy copper (Cu' in Skyline formula syntax, Cu65 in adduct syntax) …

### PR DESCRIPTION
**Pull request by bspratt**
… because it appears as an adduct in a list of common mass spec contaminants (MaConDa Contaminants DB https://www.maconda.bham.ac.uk/downloads/MaConDa__v1_0__csv.zip )

Reported by user Sangram

### CODE REVIEW

**Comment by bspratt** [comment]
It occurs to me that this could have been handled automatically if we used the information we already have in pwiz.Common.Chemistry,IsotopeAbundances.

For any given element X that we don't already have hard-coded, it's just a matter of identifying the most common stable isotopes and noting them as X', Xmm, X", and Xnn respectively, where mm and nn are the isotope masses rounded to the nearest integer.

I've opened an issue in case we want to revisit this idea.

**Comment by chambm** [comment]
Cu' and Cu65?

**Comment by bspratt** [comment]
> Cu' and Cu65? Ah I see the code has it right. The PR description had me raise an eyebrow. :)

D'oh! Fixed it, thanks

**Review by nickshulman — APPROVED** [review]

**Review by nickshulman — CHANGES_REQUESTED** [review]
I guess you also need to update "Skyline_Current.xsd" in order to pass unit tests.

Specifically, copy what is currently "Skyline_Current.xsd" to "Skyline_21.2.xsd", and then modify 
"Skyline_Current.xsd".
Also, add a new version number (21.21) to "DocumentFormat.cs" and a change "SkylineVersion.CURRENT" so that it uses that new version number.

I recommend removing the "&lt;xs:restriction>" from "atomic_symbol_type".
The restrictions that we put in the .xsd should only be for things that would actually cause a problem for Skyline if they were encountered. Basically, things that Skyline would not be able to represent in the document tree, and where Skyline should refuse to open the file.
"IsotopeEnrichments.ReadXml" will happily deal with any unknown elements that might be in that list.

**Comment by bspratt** [comment]
I think we still need the restriction for the moment - if somebody tried to introduce another heavy isotope (e.g. Fe') that we don't explicitly handle, isn't that a problem?

But yeah, one way or another I need to roll the XSD version number. Shouldn't we be moving on to 22.1 rather than 21.2, though?

**Comment by bspratt** [comment]
Of course we *could* drop that restriction if we implemented my aforementioned idea of generating comprehensive heavy isotope support based on pwiz.Common.Chemistry,IsotopeAbundances.

**Comment by brendanx67** [comment]
Let's wait for our users to tell us what they need. This seems to me like a case where adding more flexibility than is interesting to our users could impact ease-of-use. Or at least you would want to also implement "common" versus "all".

**Comment by bspratt** [comment]
>> Let's wait for our users to tell us what they need.

I feel like they have - they need more elements than we though they did, and they need more isotopes than we thought they did. With the elements we just went all in, I think we're now seeing that we should have done so with stable isotopes as well.

>> could impact ease-of-use

I don't think so - I don't propose to add these to our various pick lists. That is to say yes, we'd want to distinguish the common ones we already support from the generated ones.

I don't think it's a change users would notice. It wouldn't get added to any picklists etc.

**Comment by bspratt** [comment]
Are we good with this as it stands? The debate about comprehensive handling of less common isotopes can be tabled - I have entered an issue for that as https://skyline.ms/issues/home/issues/details.view?issueId=868

**Review by nickshulman — APPROVED** [review]
Looks good to me.
I would recommend that you change the definition of "atomic_symbol_type" in the .xsd so that it allows all strings. It will make it easier the next time we want to add support for a new element.

**Comment by bspratt** [comment]
> I would recommend that you change the definition of "atomic_symbol_type" in the .xsd so that it allows all strings. It will make it easier the next time we want to add support for a new element.

My first thought was "might as well just remove it then", and then I noticed that it doesn't actually seem to be used anywhere, so I guess I will. (If it was actually in use, I'd probably replace it with a regex though)

**Comment by bspratt** [comment]
BTW, Nick, on Monday's lab meeting call I think I understood you to be against adding any more ' and " notations - but I'm not sure what you see as the alternative? 

When I think about it, it's quite surprising that there doesn't seem to be any standard way to represent this in plaintext formulas.

**Comment by nickshulman** [comment]
> BTW, Nick, on Monday's lab meeting call I think I understood you to be against adding any more ' and " notations - but I'm not sure what you see as the alternative?
> 
> When I think about it, it's quite surprising that there doesn't seem to be any standard way to represent this in plaintext formulas.

If we allowed spaces in the chemical formula, then you could write (for very heavy glucose):
C6 2H12 18O6
but, without spaces there's no way to tell that there are not 62 carbons.

**Comment by bspratt** [comment]
Yes, or perhaps + signs as seen in adduct descriptions (though there it's all turned around, e.g. [M+6C+12H2+6O18]).

But I think we'd want to carry on with the ' and " scheme, for backward compatibility, and at that point it would be quite confusing if it worked for some elements but not others.

In any event, we could programmatically add support for the various representations using the isotope abundance table already in our code.

**Comment by bspratt** [comment]
All that aside, are you good with the changes around schema contents and version numbers? If so I'll merge.

**Pull request merged**
