### PR TITLE
Prevent intermittent TestToolService failure

### PR DESCRIPTION
**Pull request by nickshulman**
Make TestToolService more robust by rerunning the test steps if it fails the first time.

### CODE REVIEW

**Comment by brendanx67** [comment]
It appears that BRENDANX-UW7 fails this test pretty reliably when run in isolation on all 5 languages. I have not seen it reach 100 passes (i.e. 500 iterations). I have seen multiple reasons for failure. I guess I will switch to this branch to see if it helps. Have you been running the test in isolation on one of your systems? Were you able to see it failing before? How much better does this fix make the count of iterations to failure?

**Comment by nickshulman** [comment]
I have never managed to get this test to fail when I run the test hundreds of times.
When this test fails in Nightly, it always fails on the exact same line where it checks the document modification count.

I wonder whether the failure that you saw when you ran the test repeatedly in isolation was different? You wouldn't happen to have been running another instance of the test at the same time? At the start and end of the test it kills all processes with the name "TestInteractiveTool", so it would fail if your computer was running two instances of the test at the same time.

**Comment by brendanx67** [comment]
I have started a spreadsheet. I am only running one instance of the test serially. There appear to be 3 different potential failures, and it does sometimes run up to 250 passes before failing:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/brendanx/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/brendanx/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Failing Pass | Failure Type
-- | --
58 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
12 | at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
55 | at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
6 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
157 | System.InvalidOperationException: Invoke or BeginInvoke cannot be called   on a control until the window handle has been created.
79 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
106 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
162 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
232 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
225 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
241 | Expected:<1>. Actual:<0>. timed out waiting for   DocumentChangeCount==1
20 | at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
4 | at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)



</body>

</html>

**Comment by brendanx67** [comment]
When it fails the DocumentChangeCount, if you are watching with Skyline onscreen it appears to hang looking like this. Though, passing tests also show the 2 messages about "No response from Test Interactive Tool".

image

**Comment by brendanx67** [comment]
The code to try twice works great. I stopped it after 1719 passes and it had needed the second try 13 times, which you can see in the log by the runs that take over 10 seconds. Otherwise, the test runs in 1-2 seconds. It is possible that there were also failures of the quicker varieties also.

**Pull request merged**
