### PR TITLE
* copied DiaUmpire's InstrumentParameter config struct from C++ to C#

### PR DESCRIPTION
**Pull request by chambm**
* copied DiaUmpire's InstrumentParameter config struct from C++ to C# to avoid using CLI bindings to access it; hopefully this is the source of crashes after DiaUmpireTutorial tests on BSPRATT-UW2

Brian I guess you'll want to point BSPRATT-UW2's at this branch for the integration nightlies?

### CODE REVIEW

**Comment by bspratt** [comment]
I confess I don't know what's going on with this change, but I can certainly set up BSPRATT-UW2 to run this branch.

**Comment by chambm** [comment]
This change is simply porting the InstrumentParameter code, that DiaUmpire uses for its config variables, from C++ to C#. So it doesn't have to be accessed through the CLI bindings. I also removed dead code previously used to run DiaUmpire in-process in Skyline.

**Comment by bspratt** [comment]
Sounds good. Tomorrow's test reports from BSPRATT-UW2 will reflect these changes.

**Comment by chambm** [comment]
I guess we'll let integration run a few more days, but it seems to have fixed the access violation. I don't understand why not disposing the MSData from IsValidFile() would lead to any kind of corruption though. :(

**Review by bspratt — APPROVED** [review]
Excellent, once you've done the merge I'll move on with other uses for the Integration build, thanks!

**Pull request merged**
