### PR TITLE
Include tutorial audit log files in SkylineTester.zip

### PR DESCRIPTION
**Pull request by nickshulman**

### CODE REVIEW

**Review by brendanx67 — APPROVED** [review]

**Comment by bspratt** [comment]
I'm curious - why this change? There are lots of tests that will fail if you don't have the source controlled data files downloaded.

**Comment by nickshulman** [comment]
> I'm curious - why this change? There are lots of tests that will fail if you don't have the source controlled data files downloaded.

I wanted to know whether the tutorial tests would pass on a computer that did not have Visual Studio or .Net 3.5 installed. (I think it's just the ones that use Perocolator).
So far I have only run into a couple of other tests that fail, but I have not managed to run the whole test suite yet.
I don't think I've run into a test yet which is failing because the source tree is missing. The test "CodeInspection" passes if it sees that the source code directory is not there.

**Comment by bspratt** [comment]
There are at least a couple dozen that pull their data from checked-in .zip
files. I don't remember why I singled out the code inspection test like
that.

**Comment by nickshulman** [comment]
> There are at least a couple dozen that pull their data from checked-in .zip files. I don't remember why I singled out the code inspection test like that.

All .zip files from the source tree are included in SkylineTester.zip. The method "CreateZipInstallerWindow.FindZipFiles" finds them all.

**Comment by brendanx67** [comment]
The original intent of the SkylineTester artifacts was that they could pass
all tests without needing the source tree. Don Marsh designed it this way.
Especially the tutorial tests and all of the tests that show forms on the
Forms tab, because we had intended to allow professional translation
testers to use the artifacts in testing their translations. In the end, I
have had to do the translation testing, because the companies we use are
not able to handle this even with SkylineTester.

**Comment by bspratt** [comment]
Excellent, thanks for fixing the omission of the tutorial test data.

**Pull request merged**
