### PR TITLE
Skyline/work/20181203 patch 421

### PR DESCRIPTION
**Pull request by chambm**
Let's see what blows up.

### CODE REVIEW

**Comment by chambm** [comment]
Oh I thought you meant just the VENDOR_READERS preprocessor part. Sure, I'll roll back the PreferEmbeddedSpectra here.

**Comment by brendanx67** [comment]
I think just remove PR 333 and 337 from this PR

**Comment by chambm** [comment]
Happy with the changes @brendanx67  ?

**Comment by brendanx67** [comment]
Yep. Looks good. More than I was expecting, but all good. Thanks!

**Pull request merged**
