### PR TITLE
Allow PeptideShaker mzid files to lookup spectra by spectrum title

### PR DESCRIPTION
**Pull request by kaipot**
https://skyline.ms/announcements/home/support/thread.view?rowId=50606

### CODE REVIEW

**Review by nickshulman — APPROVED** [review]
Looks good to me.

**Comment by chambm** [comment]
I'm not too sure about this. MGF does not require spectrum title to be unique. That's why we use index to point into MGF. I would want to be sure that PeptideShaker chokes on an MGF that has non-unique titles, because then we'd be reasonably certain to never expect a PeptideShaker mzIdentML for an MGF with non-unique titles. Even then there's no guarantee that they won't change PeptideShaker later to handle non-unique titles.

**Comment by kaipot** [comment]
> I'm not too sure about this. MGF does not require spectrum title to be unique. That's why we use index to point into MGF. I would want to be sure that PeptideShaker chokes on an MGF that has non-unique titles, because then we'd be reasonably certain to never expect a PeptideShaker mzIdentML for an MGF with non-unique titles. Even then there's no guarantee that they won't change PeptideShaker later to handle non-unique titles.

Hmm, didn't know that about MGF. What if we keep using index for MGF but titles for other formats?

**Comment by chambm** [comment]
PeptideShaker ONLY works with MGF AFAIK: http://compomics.github.io/projects/peptide-shaker#mzidentml-support

> PeptideShaker can load results from virtually any identification algorithm in the mzIdentML format as long as the minimal peptide to spectrum match information is present in the file.
> 
> The following is required:
> 
> Spectrum file format has to be mgf.
> Each PSM has a score or e-value as a PSM score CV term.

**Comment by kaipot** [comment]
Weird, on the support request the user shared mzid/mzml results from PeptideShaker. I just tried using msconvert to convert the mzml to an mgf and that seems to work (with indices).

**Comment by kaipot** [comment]
Seems like this was a peptideshaker workflow issue rather than a BiblioSpec issue

**Pull request closed without merging**
