### PR TITLE
Fixed AssumptionException for protein group metadata

### PR DESCRIPTION
**Pull request by chambm**
- fixed AssumptionException for protein group metadata in WritePeptideGroupXml (reported by Rich)

### CODE REVIEW

**Review by nickshulman — APPROVED** [review]
Looks good to me.
Do you have any idea why more people haven't been running into this bug? Was there something unusual about Rich's document?

**Comment by chambm** [comment]
I think it's because a non-metadata-friendly protein (cRAP contaminant accession) was grouped with metadata friendly proteins (trembl/swissprot).

**Comment by chambm** [comment]
Should this be cherry-picked to release?

**Comment by nickshulman** [comment]
> Should this be cherry-picked to release?

Yes. This fix should probably be cherry picked to release. It's possible we won't ever release another 22.2 patch but if we do release one it would be good for this fix to be in it.

**Pull request merged**
