### PR TITLE
* added support for parallelmode to SkylineTester

### PR DESCRIPTION
**Pull request by chambm**
* added support for parallelmode to SkylineTester including building chambm/always_up_runner for first time users and killing Docker workers when pressing "Stop"

* added simple password hiding to KeyValueGridDlg (if key contains "password" so not really localized)
* moved some TestRunner parallelization functions to TestRunnerLib so they can be used in SkylineTester
* added CloseMainWindow() call for ProcessUtilites.Kill() to allow managed process to clean up gracefully (this was intended to let TestRunner clean up its own Docker workers but catching the "close window" event did not seem to work very well)

### CODE REVIEW

**Review by brendanx67 — APPROVED** [review]
Looks okay and it worked for me. Definitely makes it more usable.

**Comment by chambm** [comment]
Wow that did not do what it was supposed to do.

**Pull request merged**
