### PR TITLE
Restructure Tutorial Image naming

### PR DESCRIPTION
**Pull request by eduardo-proteinms**
This restructuring is automated so we can rerun if if we need to change the source before we merge this.

This PR changes the following:
- Moves icon/button images to shared folder
- Names all images which are not coming from Skyline using the format "s-name"
- All other images are renamed / renumbered to the format "s-#"

This will make it simpler to output images from tutorial tests with a counter for now. Also we can use the s- prefix to add alt text / anchors in html programmatically

Example:
image

### CODE REVIEW

**Comment by eduardo-proteinms** [comment]
Will rerun script once #3180 is merged

**Comment by brendanx67** [comment]
Looks great. Definitely an improvement on several levels. Please start the s-# with s-1 instead of s-0. These are not indices into an array. I know the # from s-# will not line up with "Figure #", but I still think it is better to have the s-# and Figure # both start with 1.

**Comment by brendanx67** [comment]
I have merged PR #3180

**Comment by eduardo-proteinms** [comment]
> Looks great. Definitely an improvement on several levels. Please start the s-# with s-1 instead of s-0. These are not indices into an array. I know the # from s-# will not line up with "Figure #", but I still think it is better to have the s-# and Figure # both start with 1.

Numbering starts at 1 now. This should be ready for merge.

**Pull request merged**
