### PR TITLE
Update expected values in DiaSwathTutorialTest

### PR DESCRIPTION
**Pull request by nickshulman**
Change the expected values for the test DiaSwathTutorialTest.
These numbers changed slightly as a result of PR #2503

### CODE REVIEW

**Review by brendanx67 — CHANGES_REQUESTED** [review]
This probably means that numbers (possibly screenshots) need to be updated in the tutorial DOC files.

**Comment by nickshulman** [comment]
> This probably means that numbers (possibly screenshots) need to be updated in the tutorial DOC files.

Yep, product and the tutorial diverged a lot in July, 2022 starting on page 12:

Old picture:
image
Current picture:
image

**Comment by brendanx67** [comment]
Yeah. Huh. I updated all of those tutorials for Kaipo's changes to the
Import Peptide Search wizard, but it looks like only the DDA search
tutorial got updated with Matt's new Associate Proteins form. Looks like
the 4 DIA-related tutorials all need to be updated. I can give that a crack
on this PR.

**Comment by brendanx67** [comment]
Actually, I will do it on the 22.2 branch first.

**Pull request merged**
